export const CHAT_FETCH_MESSAGES_REQUEST = 'CHAT_FETCH_MESSAGES_REQUEST';
export const CHAT_FETCH_MESSAGES_SUCCESS = 'CHAT_FETCH_MESSAGES_SUCCESS';
export const CHAT_FETCH_MESSAGES_FAIL = 'CHAT_FETCH_MESSAGES_FAIL';

export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_FAIL = 'CHAT_SEND_MESSAGE_FAIL';
